Models/RelationshipGroupRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MainBit.Relationships.Models
{
    public class RelationshipGroupRecord
    {
        public virtual int Id { get; set; }
        [Required]
        public virtual string Title { get; set; }
    }
}

Models/RelationshipRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement.Records;

namespace MainBit.Relationships.Models
{
    public class RelationshipRecord
    {
        public virtual int Id { get; set; }
        public virtual int RelationshipGroupRecord_Id { get; set; }
        public virtual int ContentItemRecord1_Id { get; set; }
        public virtual int ContentItemRecord2_Id { get; set; }
    }
}

ViewModels/RelationshipFieldViewModel.cs
using System.Collections.Generic;
using Orchard.ContentManagement;
using MainBit.Relationships.Fields;

namespace MainBit.Relationships.ViewModels
{
    public class RelationshipFieldViewModel
    {
        public ICollection<ContentItem> ContentItems { get; set; }
        public string SelectedIds { get; set; }
        public RelationshipField Field { get; set; }
        public ContentPart Part { get; set; }
    }
}

Controllers/RelationshipGroupAdminController.cs
using System.Web.Mvc;
using Orchard;
using Orchard.Localization;
using Orchard.Security;
using Orchard.UI.Admin;
using Orchard.UI.Notify;
using MainBit.Relationships.Services;
using MainBit.Relationships.Models;

namespace MainBit.Relationships.Controllers
{
    [ValidateInput(false), Admin]
    public class RelationshipGroupAdminController : Controller 
    {
        private readonly IRelationshipGroupService _relationshipGroupService;

        public RelationshipGroupAdminController(IRelationshipGroupService relationshipGroupService, IOrchardServices orchardServices)
        {
            _relationshipGroupService = relationshipGroupService;
            Services = orchardServices;
            T = NullLocalizer.Instance;
        }

        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        [HttpGet]
        public ActionResult Index() {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            var listOfRecords = _relationshipGroupService.Get();
            if (listOfRecords == null || listOfRecords.Count == 0)
                ViewBag.EmptyMessage = T("No data");
            return View(listOfRecords);
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            var model = new RelationshipGroupRecord();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(RelationshipGroupRecord model)
        {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            model.Id = 0;

            if (!ModelState.IsValid)
                return View();

            _relationshipGroupService.Create(model);
            Services.Notifier.Information(T("MainBit relationship group successfully added"));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int relationshipGroupId)
        {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            return View(_relationshipGroupService.Get(relationshipGroupId));
        }

        [HttpPost]
        public ActionResult Edit(int relationshipGroupId, RelationshipGroupRecord model)
        {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            model.Id = relationshipGroupId;

            if (!ModelState.IsValid)
                return View(model);

            _relationshipGroupService.Update(model);
            Services.Notifier.Information(T("MainBit relationship group successfully saved"));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int relationshipGroupId)
        {
            if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Cannot manage MainBit relationship groups")))
                return new HttpUnauthorizedResult();

            _relationshipGroupService.Delete(relationshipGroupId);
            Services.Notifier.Information(T("MainBit relationship group successfully deleted"));

            return RedirectToAction("Index");
        }

    }
}

Views/DefinitionTemplates/RelationshipFieldSettings.cshtml
@model MainBit.Relationships.Settings.RelationshipFieldSettings

<fieldset>
    <div>
        @Html.CheckBoxFor(m => m.Required) <label for="@Html.FieldIdFor(m => m.Required)" class="forcheckbox">@T("A content item is required")</label>
        <span class="hint">@T("Check to ensure the user is providing at least one content item.")</span>
    </div>
</fieldset>
<fieldset>
    <div>
        @Html.CheckBoxFor(m => m.Multiple) <label for="@Html.FieldIdFor(m => m.Multiple)" class="forcheckbox">@T("Allow multiple content items")</label>
        <span class="hint">@T("Check to allow the user to select multiple content items.")</span>
    </div>
</fieldset>
<fieldset>
    <div>
        @Html.CheckBoxFor(m => m.HideEditor) <label for="@Html.FieldIdFor(m => m.HideEditor)" class="forcheckbox">@T("Hide field in edit content item")</label>
        <span class="hint">@T("Check to hide field in edit content item.")</span>
    </div>
</fieldset>
<fieldset>
    <label for="@Html.FieldIdFor(m => m.Hint)">@T("Help text")</label>
    @Html.TextAreaFor(m => m.Hint, new { @class = "textMedium", rows = "5" } )
    <span class="hint">@T("The help text is written under the field when authors are selecting content items.")</span>
    @Html.ValidationMessageFor(m => m.Hint)
</fieldset>
<fieldset>
    @Html.LabelFor(m => m.RelationshipGroupRecord_Id, T("Relationship group"))
    @Display.RelationshipGroupPicker(Value: Model.RelationshipGroupRecord_Id)
    <span class="hint">@T("Specify a relationship group")</span>
</fieldset>
<fieldset>
    <div>
        <label for="@Html.FieldIdFor(m => m.DisplayedContentTypes)">@T("Content Types and Parts")</label>
        @Html.TextBoxFor(m => m.DisplayedContentTypes)
        <span class="hint">@T("A comma separated value of all the content types or content parts to display.")</span>
    </div>
</fieldset>

Views/EditorTemplates/Fields/Relationship.cshtml
@model MainBit.Relationships.ViewModels.RelationshipFieldViewModel
@using Orchard.Utility.Extensions;
@using MainBit.Relationships.Settings;

@{
    Script.Require("ContentPicker").AtFoot();
    Script.Require("jQueryUI_Sortable").AtFoot();
    Style.Include("content-picker-admin.css");

    RelationshipFieldSettings settings = Model.Field.PartFieldDefinition.Settings.GetModel<RelationshipFieldSettings>();
}
@Display.ContentPicker_Edit(
    Required: settings.Required,
    Multiple: settings.Multiple,
    DisplayName: Model.Field.DisplayName,
    IdsFieldId: "test-work-without-it", //Html.FieldIdFor(m => m.Field.Ids),
    SelectedItemsFieldName: Html.FieldNameFor(m => m.SelectedIds),
    ContentItems: Model.ContentItems,
    Hint: settings.Hint,
    PartName: Model.Part.PartDefinition.Name,
    FieldName: Model.Field.PartFieldDefinition.Name
)

Views/Fields/Relationship.SummaryAdmin.cshtml
@using MainBit.Relationships.Fields
@using Orchard.Utility.Extensions;

@{
    var field = (RelationshipField) Model.ContentField;
    string name = field.DisplayName;
    var contentItems = field.ContentItems;
}
<p class="content-picker-field content-picker-field-@name.HtmlClassify()">
    <span class="name">@name:</span>
    @if(contentItems.Any()) {
        foreach(var contentItem in contentItems) {
            <span class="value">@Html.ItemEditLink(contentItem)</span>
            if(contentItem != contentItems.Last()) {
                <span>,</span>
            }
        }
    }
    else {
        <span class="value">@T("No content items.")</span>
    }
</p>

Views/Fields/Relationship.cshtml
@using MainBit.Relationships.Fields
@using Orchard.Utility.Extensions;

@{
    var field = (RelationshipField) Model.ContentField;
    string name = field.DisplayName;
    var contentItems = field.ContentItems;
}
<p class="content-picker-field content-picker-field-@field.Name.HtmlClassify()">
    <span class="name">@name:</span>
    @if(contentItems.Any()) {
        foreach(var contentItem in contentItems) {
            <span class="value">@Html.ItemDisplayLink(contentItem)</span>
            if(contentItem != contentItems.Last()) {
                <span>,</span>
            }
        }
    }
    else {
        <span class="value">@T("No content items.")</span>
    }
</p>

Views/RelationshipGroupAdmin/Create.cshtml
@model MainBit.Relationships.Models.RelationshipGroupRecord
<h1>@Html.TitleForPage(T("Create new relationship group").ToString())</h1>
@using (Html.BeginFormAntiForgeryPost())
{
    @Html.ValidationSummary()
    <fieldset>
        <label for="@Html.IdFor(m => m.Title)">@T("Title")</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "text medium" })
        <span class="hint">@T("Title")</span>
    </fieldset>
    <button class="primaryAction" type="submit" name="submit.Save" value="submit.Save">@T("Save")</button>
    <a href="@Url.Action("Index")" class="button">@T("Cancel")</a>
}

Views/RelationshipGroupAdmin/Edit.cshtml
@model MainBit.Relationships.Models.RelationshipGroupRecord
<h1>@Html.TitleForPage(T("Edit relationship group").ToString())</h1>
@using (Html.BeginFormAntiForgeryPost())
{
    @Html.ValidationSummary()
    <fieldset>
        <label for="@Html.IdFor(m => m.Title)">@T("Title")</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "text medium" })
        <span class="hint">@T("Title")</span>
    </fieldset>
    <button class="primaryAction" type="submit" name="submit.Save" value="submit.Save">@T("Save")</button>
    <a href="@Url.Action("Index")" class="button">@T("Cancel")</a>
}

Views/RelationshipGroupAdmin/Index.cshtml
@model List<MainBit.Relationships.Models.RelationshipGroupRecord>
    <h1>@Html.TitleForPage(T("Relationship Groups").ToString())</h1>
    @ViewBag.EmptyMessage
    @if (Model != null && Model.Count > 0)
{
    <table class="items">
        <thead>
            <tr>
                <th>@T("Id")</th>
                <th>@T("Title")</th>
                <th>@T("Actions")</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>
                    <a href="@Url.Action("Edit", "RelationshipGroupAdmin", new { relationshipGroupId = item.Id })">@T("Edit")</a> | <a href="@Url.Action("Delete", "RelationshipGroupAdmin", new { relationshipGroupId = item.Id })">@T("Remove")</a>
                </td>
            </tr>
        }
</table>
}
<fieldset>
    @Html.ActionLink(T("Create").ToString(), "Create", new { }, new { @class = "button" })
</fieldset>

Views/RelationshipGroupPicker.cshtml
@using System.Linq
@using Orchard.ContentManagement;
@using Orchard.ContentManagement.Aspects;
@using MainBit.Relationships.Models;
@{
    var relationshipGroups = (List<RelationshipGroupRecord>)Model.RelationshipGroups;
    var currentValue = Model.Value == null ? 0 : (int)Model.Value;
    var options = relationshipGroups.Select(x => new SelectListItem
    {
        Text = x.Title, //x.As<ITitleAspect>().Title,
        Value = x.Id.ToString(),
        Selected = x.Id == currentValue 
    });
    var name = Model.Name != null ? Model.Name as string : "RelationshipGroupRecord_Id";
    
}
@Html.DropDownList(name, options, T("Select an option").ToString())